/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK 0x0800U /*!< Select GPIO1 or GPIO2: affected bits mask */

/* GPIO_11 (number 1), ledCikis */
/* Routed pin properties */
#define BOARD_INITPINS_ledCikis_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ledCikis_SIGNAL                                gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_ledCikis_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_02 (number 11), PCA9685_SCL */
/* Routed pin properties */
#define BOARD_INITPINS_PCA9685_SCL_PERIPHERAL                             LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_PCA9685_SCL_SIGNAL                                    SCL   /*!< Signal name */

/* GPIO_01 (number 12), PCA9685_SCL */
/* Routed pin properties */
#define BOARD_INITPINS_PCA9685_SDA_PERIPHERAL                             LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_PCA9685_SDA_SIGNAL                                    SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
